# Generated by Django 3.2 on 2021-05-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_number', models.IntegerField()),
                ('distance_value', models.IntegerField()),
                ('timeStamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reflectance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_value1', models.IntegerField()),
                ('sensor_value2', models.IntegerField()),
                ('sensor_value3', models.IntegerField()),
                ('sensor_value4', models.IntegerField()),
                ('sensor_value5', models.IntegerField()),
                ('sensor_value6', models.IntegerField()),
                ('sensor_value7', models.IntegerField()),
                ('timeStamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
